### ISSUE TITLE
【機能】プラグイン埋込み型 KPM用設定ファイル

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [TeamKun/TeamKUNPluginManager#79]
### 詳細

+ インストール・アンインストール・アップデート 時に必要な操作を定義する設定ファイルのサポートを行います。
+ プラグインのビルド時に, プラグイン.jar 直下に `kpm.yml` ファイルを配置します。
+ `plugin.yml` の拡張として想定します。

### 例
```yml
# 対応するKPMのバージョンです。
# この例では, v3.0.0 以上のKPMでサポートされます。
kpm: v3.0.0 

# アップデートに使用するクエリを指定します。
update: gh>ExampleOrganization/ExamplePlugin

# フックを指定します。( フックについては #80 を参照)
hooks:
-  org.example.exampleplugin.KPMHook
-  org.example.exampleplugin.hoge.Hook

# 依存関係解決に使用するソースです。
# 複数の依存関係が同じソースで利用可能な場合, dependenciesの記述を省略できます。
sources:
- type: github
  organization: ExampleOrganization

# プラグインが使用するレシピの名前空間です。
# Bukkitが自動で割り当てた空間は自動で指定されます。
recipes:
- org.example.recipes

dependencies:
- name: ExampleLibrary
  # 推奨。依存関係の収集の際のクエリを指定します。
  # query または url のどちらかを指定します。
  query: gh>ExampleOrganization/ExampleLibrary  

  # 非推奨。依存関係のHTTP(HTTPS) プロトコルの直リンクを指定します。
  # query または url のどちらかを指定します。
  url: https://example.com/lib/ExampleLibrary-1.0.0.jar

  # 対応する依存関係のバージョンを指定します。
  # セマンティック・バージョニング 記法をサポートします。
  version: ^1.0.0
```

## 関連
+ [#80 【機能】実行可能な任意のKPMフック](https://github.com/TeamKun/TeamKUNPluginManager/issues/80)
